### PR TITLE
Optimize the whitepaper PDF

### PR DESCRIPTION
**Pull request by Selicre**
One whole kilobyte? We have no time for such bloat. This pull request optimizes the whitepaper PDF to the smallest possible version that retains the original paper size, opens correctly in both Firefox and Chrome, and also is detected as a pdf by github so it gets served with the correct mime type.

This doesn't actually open properly in Acrobat Reader, but who cares.

### CODE REVIEW

**Comment by zhuowei** [comment]
Thank you so much! I'm probably going to keep the current version, but if I have time I'll try to debug why this doesn't work in Acrobat Reader.

**Comment by Selicre** [comment]
It's likely because both firefox and chrome are rather permissive with terminating brackets, but Acrobat Reader itself isn't.

**Comment by trillllian** [comment]
already working on acrobat support right now ;)

**Comment by zhuowei** [comment]
Thanks.
To be honest, I'm probably not going to merge this, since using 994 bytes to display absolutely nothing is very much in agreement with the blockchain ethos.
However, my next project will be a PDF based project (since I was amazed by rsnous's [Breakout game in a PDF](https://twitter.com/rsnous/status/750019120159072256) demo and would like to try something similar) so I'm interested in learning PDF tricks for the future.

**Comment by Selicre** [comment]
Well, rand made it open in acrobat reader anyway, if nothing else, this was fun. Acrobat still cowers in fear and tries to re-save it as a 4kB monstrocity, but hey, it works.

**Pull request closed without merging**
